# Generated by cucumber-sinatra. (2014-05-25 06:35:05 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/server.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'database_cleaner'
require 'factory_girl'
require_relative '../../spec/factories/user'


def app
  Sinatra::Application
end

Capybara.app = app

DatabaseCleaner.strategy = :transaction

class ChitterWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
  include FactoryGirl::Syntax::Methods
end

World do

  ChitterWorld.new
end

