# Generated by cucumber-sinatra. (2014-05-25 06:35:05 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'chitter.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

def app
  Sinatra::Application
end

Capybara.app = app

class ChitterWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ChitterWorld.new
end
